project:
  type: website
  output-dir: docs
  render: 
    - index.qmd
website:
  google-analytics: "G-LZ35J3XE4D"
  announcement: 
    icon: info-circle
    dismissable: true
    content: "Thanks for investigating!"
    type: info
    position: below-navbar 
  page-navigation: true 
  title: "Cytometry in R"
  navbar:
    logo: images/hex.svg
    background: white
    right:
    - icon: youtube
      href: https://www.youtube.com/@CytometryInR
      aria-label: YouTube
    - icon: github
      href: https://github.com/DavidRach/FlowGate_Testing
      aria-label: GitHub
  page-footer: 
   left: Made with [Quarto](https://quarto.org/)
format:
  html:
    css: styles.css

